name: Deploy Laravel Project on push

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v2.3.2

      - uses: actions/setup-node@v3  # Use stable version

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install --no-dev --prefer-dist --ignore-platform-reqs

      - name: Run Artisan Commands
        run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan route:clear
          php artisan view:clear
          php artisan storage:link

      - name: Directory Permissions (production)
        run: chmod -R 775 storage bootstrap/cache

      - name: Generate key
        run: php artisan key:generate

      - name: 📂 Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          server-dir: /public_html/nonton-film-laravel-10/

      - name: Run migrations (optional)
        run: php artisan migrate --force  # Use --force in production to prevent accidental confirmation prompts

      - name: Set up authentication for Composer
        run: |
          echo '{"github-oauth": {"github.com": "${{ secrets.TOKEN }}"}}' > ~/.composer/auth.json
