on:
  push:
    branches:
      - main
name: 🚀 Deploy website
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}        # Pastikan ini diatur di Secrets
        username: ${{ secrets.USERNAME }}        # Pastikan ini diatur di Secrets
        password: ${{ secrets.PASSWORD }}        # Pastikan ini diatur di Secrets
        server-dir: /public_html/nonton-film-laravel-10/               # Periksa apakah direktori ini ada di server